include:
  - project: cloudbear/ci
    ref: master
    file: /base/base.yml
  - project: cloudbear/ci
    ref: master
    file: /base/image.yml
  - project: cloudbear/ci
    ref: master
    file: /templates/prepare-release/semantic-release.yml

dependencies:
  stage: dependencies
  image: golang
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  interruptible: true
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TITLE !~ /chore\(release\)\: version/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script: go mod vendor
  cache:
    key:
      files:
        - go.mod
        - go.sum
    paths:
      - .go/pkg/mod/
      - vendor
  artifacts:
    expire_in: 1h
    paths:
      - vendor

build:
  extends:
    - .base-build-image
  needs:
    - dependencies

unit-tests:
  stage: test
  image: golang:1.14.14-alpine
  interruptible: true
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TITLE !~ /chore\(release\)\: version/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    CGO_ENABLED: 0
  script: go test -v -coverprofile .testCoverage.txt github.com/coreos/etcd-operator/pkg/... 2>&1 | tee output
  after_script:
    - go get -u github.com/jstemmer/go-junit-report
    - cat output | go-junit-report > report.xml
  coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
  needs:
    - dependencies
  artifacts:
    when: always
    reports:
      junit: report.xml

release:
  extends:
    - .base-release-image
  needs:
    - build
